### ISSUE TITLE
Compile with exceptions enabled

### ISSUE THREAD

**Issue by nicholascc** [codecat/qb#9]
This project has proven really useful for me; I was able to set up compilation on Windows very easily and so far there's been far less hassle than either using Visual Studio directly or using a custom build script.

The one problem I've run into is exception handling. When qb compiles my project, it doesn't use any [flags for exception handling](https://docs.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=vs-2019) and there's no way to set it to handle exceptions in the way used by default by visual studio. It would be very useful to have some sort of option in qb to set the flags for exception handling used by visual studio (I would use the flag `/EHsc`).

I'm not sure if this flag should just be a single compiler option, because there are other instances where I might want to have more control over what the compiler is doing (such as changing the optimization level, etc.), so maybe there's a way to generalize it to other flags.

**Comment by codecat** [comment]
Interesting idea! I've been thinking about this for a bit, and I think `/EHsc` is probably a reasonable default on MSVC.

So I'm thinking of doing the following things:

* Adding `/EHsc` to the default compiler flags on MSVC (need to test how much this will impact compile time and resulting binary size though, but I expect it not to be too much of an issue)
* Adding an option to switch between exception handling modes (similar to premake's `exceptionhandling` option)
* Adding the ability to pass any compiler and linker flags (with some kind of compiler-specific filter)

I've been thinking about optimization flags as well, which I would probably enable by default unless the `--debug` flag is given.

**Comment by codecat** [comment]
I've made some changes that add an option `exceptions`, where the default on Windows is `standard`, which compiles with `/EHsc`.

There's also a new `optimize` option to change the optimizations used. By default, it's an optimized build unless `--debug` is given, then it's unoptimized.

Released 1.0.1 with these changes as well! 🎉 https://github.com/codecat/qb/releases

I haven't added a "general" way to add flags yet, because I'm still unsure how to do it the best way. I opened issue #10 for this.
